insert into institutions (id, title, category, link, notes, template, required_fields) values
('dvla-licence','DVLA – Driving licence','gov',
 'https://www.gov.uk/change-address-driving-licence',
 'Have licence number & previous address ready. Update after you move.',
 'Please update my driving licence address to: {{full_name}}, {{new_address}}. Move date: {{move_date}}.',
 '{full_name,new_address,move_date,driving_licence_no}'),
('dvla-v5c','DVLA – V5C vehicle keeper','gov',
 'https://www.gov.uk/change-address-v5c',
 'You need the V5C log book to change keeper address.',
 'Change vehicle keeper address to {{new_address}} effective {{move_date}}.',
 '{new_address,move_date}'),
('hmrc','HMRC – Personal Tax','gov',
 'https://www.gov.uk/tell-hmrc-change-address',
 'Sign in to your Personal Tax Account to update address.',
 'Update my HMRC address to {{new_address}} as of {{move_date}}.',
 '{new_address,move_date}'),
('council-tax','Council tax – new council setup','gov',
 'https://www.gov.uk/find-local-council',
 'Find your local council and complete the Moving Home form.',
 'New occupier: {{full_name}} at {{new_address}} from {{move_date}}.',
 '{full_name,new_address,move_date}'),
('gp','NHS – GP registration','health',
 'https://www.nhs.uk/nhs-services/gps/how-to-register-with-a-gp-surgery/',
 'Find a local GP and register (GMS1).',
 'Please register me at your practice. Name: {{full_name}}, Address: {{new_address}}.',
 '{full_name,new_address}'),
('dentist','NHS – Dentist registration','health',
 'https://www.nhs.uk/service-search/find-a-dentist',
 'Find a local NHS dentist. Some have waiting lists.',
 'Registration enquiry for {{full_name}}, new address: {{new_address}}.',
 '{full_name,new_address}'),
('voter','Voter registration','gov',
 'https://www.gov.uk/register-to-vote',
 'Takes ~5 minutes; NI number helpful.',
 'Register to vote at {{new_address}}.',
 '{new_address}'),
('tv-licence','TV Licence – change address','gov',
 'https://www.tvlicensing.co.uk/cs/update-your-details/update-your-details.index.htm',
 'Have TV Licence number and old postcode.',
 'Update TV Licence to {{new_address}}.',
 '{new_address}'),
('bank','Bank(s) – secure message template','finance',
 'https://www.google.com/search?q=your+bank+change+address+secure+message',
 'Send via your bank’s secure message or address details page.',
 'Please update my correspondence address to {{new_address}} effective {{move_date}}.',
 '{new_address,move_date}'),
('utilities-broadband','Utilities & Broadband','utility',
 'https://www.uswitch.com/energy/',
 'Compare tariffs/speeds for your new postcode.',
 'Switch to best tariff at {{new_address}}; preferences: {{preferences}}.',
 '{new_address,preferences}'),
 ('clubs-societies','Clubs & Societies (sports, gyms, professional bodies, charities)','community',
 'https://www.google.com/maps',
 'Find local clubs, gyms, and societies near your new postcode.',
 'Interests: {{clubs_interests}}. Postcode: {{new_postcode}}. Please send joining details / trial info.',
 '{new_postcode,clubs_interests}')
on conflict (id) do nothing;
